[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.ipynb
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | venv
  | buck-out
  | build
  | dist
  | miniconda
)/
'''
